version: '3.3'
services:
  db:
    image: postgres
    restart: always
    ports:
      - "54321:5432"
    env_file:
      - .env

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '63791:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data
volumes:
  cache:
    driver: local