"""add post 7

Revision ID: e4ef83e1fc7d
Revises: 3f99e3e0b5bb
Create Date: 2023-06-12 13:58:11.398371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4ef83e1fc7d'
down_revision = '3f99e3e0b5bb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
