"""add post 5

Revision ID: 5bd99eb2aad5
Revises: ebc86844c602
Create Date: 2023-06-12 13:56:36.778222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bd99eb2aad5'
down_revision = 'ebc86844c602'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
