"""add post 9

Revision ID: cecd88fa1fa5
Revises: e4ef83e1fc7d
Create Date: 2023-06-12 13:59:12.900869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cecd88fa1fa5'
down_revision = 'e4ef83e1fc7d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
