"""add post 6

Revision ID: 3f99e3e0b5bb
Revises: 5bd99eb2aad5
Create Date: 2023-06-12 13:57:37.026355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f99e3e0b5bb'
down_revision = '5bd99eb2aad5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
