"""add post 3

Revision ID: 65cc80d86975
Revises: 2511ba457c59
Create Date: 2023-06-12 12:45:17.280576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65cc80d86975'
down_revision = '2511ba457c59'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
