"""4

Revision ID: 9069758d6f24
Revises: 9d5ac980cce4
Create Date: 2023-06-11 16:17:59.697801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9069758d6f24'
down_revision = '9d5ac980cce4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'video', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'video', type_='foreignkey')
    op.drop_column('video', 'user_id')
    # ### end Alembic commands ###
