"""2

Revision ID: 987f21ef711f
Revises: ad5dda34886d
Create Date: 2023-06-11 15:59:42.272331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '987f21ef711f'
down_revision = 'ad5dda34886d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
