"""add model post

Revision ID: d93a6c383a0d
Revises: 9069758d6f24
Create Date: 2023-06-12 12:22:49.188261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd93a6c383a0d'
down_revision = '9069758d6f24'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
